### ISSUE TITLE
Integration?

### ISSUE THREAD

**Issue by gdi2290** [GlobalWebIndex/segment#13]
how does this work with Integration?

**Comment by turboMaCk** [comment]
Hi @gdi2290,

unlike official segment library, this one doesn't embed other 3rd party stuff but uses segment's API (similar to a segment for node.js). This means that distribution of event happens from segment's backend service not directly from a client. In practice, this means that all tracks are distributed according to your settings in segment.io (integrations turned off). However, if you're using something like Intercom which comes with its own UI as well you need to integrate their official library in order to get that UI. Then all tracks are distributed using `gwi-segment` but actually chat is integrated directly using Intercom.

hope it answers your question. Otherwise, let me know and I'll reopen this issue.
